### PR TITLE
Add clang-format 10 from https://github.com/muttleyxd/clang-format-st…

### LINKED ISSUE #9: add clang-format 10.0
add clang-format 10.0

### PR DESCRIPTION
**Pull request by jsharpe**
…atic-binaries/releases/download/master-5b56bb49/clang-format-10_linux-amd64. Closes #9

---
This change is [Reviewable](https://reviewable.io/reviews/doozyx/clang-format-lint-action/10)

### CODE REVIEW

**Comment by wenzeslaus** [comment]
I have tested the check sum of the binary file in this PR is OK:

```
$ wget https://github.com/DoozyX/clang-format-lint-action/raw/61f6a826e466b1e8162aa73100bc9020ce288af1/clang-format/clang-format10
$ mv clang-format10 clang-format-10_linux-amd64
$ sha512sum --check clang-format-10_linux-amd64.sha512sum 
clang-format-10_linux-amd64: OK
```

**Comment by wenzeslaus** [comment]
Works for me locally:

```
$ docker build -t jsharpe/clang-format-lint-action "https://github.com/jsharpe/clang-format-lint-action.git#clang-format10"
$ docker run -it --rm --workdir /src -v $(pwd):/src jsharpe/clang-format-lint-action --clang-format-executable /clang-format/clang-format10 -r --exclude .git *.hpp *.cpp
```

**Comment by DoozyX** [comment]
Thank you. sorry for waiting

**Comment by steven-johnson** [comment]
When I try using this version (via `clangFormatVersion:10`), it fails with `run-clang-format.py: error: Command '/clang-format/clang-format10 --version' failed to start: [Errno 2] No such file or directory: '/clang-format/clang-format10'`

See https://github.com/halide/Halide/pull/5122/checks?check_run_id=874907072 for an example.

**Comment by wenzeslaus** [comment]
So far, I have just tried using it directly through Docker and that works.

````
docker build -t doozyx/clang-format-lint-action "github.com/DoozyX/clang-format-lint-action"
docker run --rm --workdir /src -v $(pwd):/src doozyx/clang-format-lint-action --clang-format-executable /clang-format/clang-format10 -r --exclude .git *.cpp

**Comment by jsharpe** [comment]
@steven-johnson This change hasn't been included in a release yet so you'll have to reference the commit sha directly in your github action config to pick up this change.

**Comment by steven-johnson** [comment]
Woops! Sorry, my bad, I hadn't realized it wasn't part of a release. Trying now.

**Comment by steven-johnson** [comment]
Works perfectly now! Thanks!

**Pull request merged**
