### PR TITLE
Add clang-format-14

### PR DESCRIPTION
**Pull request by bernhardmgruber**
From: https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-208096c1/clang-format-14_linux-amd64

Fixes: #39

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
Ping.

**Comment by DoozyX** [comment]
Thank sorry, was little busy, will test the app and release a new version later

**Comment by DoozyX** [comment]
published new release, sorry thought I needed to include some my changes but it works fine with just yours (just tested it)

**Comment by bernhardmgruber** [comment]
No need to be sorry! I am happy you provide this great GitHub action! :) Thank you for the release!

**Pull request merged**
