### PR TITLE
fix: Remove `distutils.strtobool` and replace with `BooleanOptionalAction``

### LINKED ISSUE #73: Distutils has been removed from Python 3.12
Starting with Python 3.12, Distutils has been removed https://peps.python.org/pep-0632/
It looks like the docker image python:3-alpine is based on 3.12, so this action no longer works.

Could you upgrade the Python script, or as a quick workaround use the python:3.11-alpine image?

Thanks

### PR DESCRIPTION
**Pull request by GeckoEidechse**
Same as #74 but without the formatting changes

Closes #73

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Made sure to co-author you @levtoji as all I did was revert the formatting changes done by `ruff` ^^"

**Review by echoix — APPROVED** [review]
It looks like the correct usage for argparse.BooleanOptionalAction
according to https://docs.python.org/3/library/argparse.html.

It will work with Python 3.9 and later.

It should solve the complete action failure that suddenly started occurring even though we fully pin our actions and dependencies. Does that mean that the docker image was replaced, or the docker image is built each time on the user's side, without pinning?

**Comment by eguiraud-pf** [comment]
@echoix the docker image is here: https://github.com/DoozyX/clang-format-lint-action/blob/master/Dockerfile

it's using `FROM python:3-alpine` which does not fix Python's minor version. See also https://github.com/DoozyX/clang-format-lint-action/issues/73#issuecomment-2329464327

**Comment by echoix** [comment]
> @echoix the docker image is here: https://github.com/DoozyX/clang-format-lint-action/blob/master/Dockerfile
> 
> 
> 
> it's using `FROM python:3-alpine` which does not fix Python's minor version. See also https://github.com/DoozyX/clang-format-lint-action/issues/73#issuecomment-2329464327

It's not an "image", it's a Dockerfile. The action.yml points to use a Dockerfile https://github.com/DoozyX/clang-format-lint-action/blob/caa179272c6ee7f1d25dfb503ee0c410c26ebd98/action.yml#L34 instead of a built image, published in a registry (that doesn't change, unless pushed over it, but the digest would change). That means that we loose the reproductibility of Docker containers (each user at each run has a different build).

**Comment by eguiraud-pf** [comment]
sure, just wanted to say the reason this happened with how things are structured currently is that the minor python version is not pinned

**Comment by DoozyX** [comment]
Thanks, but this caused some other issues running the Python script, reverted it and pinned the docker version. It should be working as before now.

**Comment by GeckoEidechse** [comment]
> Thanks, but this caused some other issues running the Python script, reverted it and pinned the docker version. It should be working as before now.

Whoopsie, that's on me. Glad that pinning it solved the issue for now at least. Thanks for your work on this <3

**Comment by eguiraud-pf** [comment]
yep, thank you for the quick reaction @DoozyX !

**Pull request merged**
