### PR TITLE
Add clang-format 17.0.2

### PR DESCRIPTION
**Pull request by alemuntoni**

### CODE REVIEW

**Comment by offa** [comment]
@DoozyX could you have a look at this PR? Latest clang-format would be appreciated :-).

**Review by DoozyX — CHANGES_REQUESTED** [review]
can you fix the link?

**Comment by alemuntoni** [comment]
Ooops! Sorry, didn't see that! I just fixed it.

**Comment by DoozyX** [comment]
thanks, but still don't think it is working as expected, are you testing it on unix, this is what I got 
image

**Comment by DoozyX** [comment]
also where does the binary come from, for consistency can you align it with https://github.com/muttleyxd/clang-tools-static-binaries?

**Comment by alemuntoni** [comment]
> also where does the binary come from

I downloaded it from the official llvm release on github, since I did not find anywhere from where they came from.

I will align the binary from the link you provided.

**Comment by DoozyX** [comment]
thanks, in that case just posting the link should be fine

**Comment by alemuntoni** [comment]
I replaced the binary with the one provided in the https://github.com/muttleyxd/clang-tools-static-binaries repo, which is version 17.0.4.

**Comment by DoozyX** [comment]
Also the binary needs to be executable (needs chmod +x)

**Comment by alemuntoni** [comment]
> Also the binary needs to be executable (needs chmod +x)

Ops again :D Sorry!

It should be ok now!

**Comment by GeckoEidechse** [comment]
bump

**Comment by GeckoEidechse** [comment]
Closes #64

**Comment by DoozyX** [comment]
Thanks

**Pull request merged**
